model:
  - DeepMultisets
device:
  - cuda
batch_size:
  - 32
hidden_units:
  - 32
  - 128
learning_rate:
  - 0.01
  - 0.1
l2:
  - 0.001
  - 0.01
classifier_epochs:
  - 100
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
